# Generated by Django 6.0.4 on 2026-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('preview', models.ImageField(upload_to='images/', verbose_name='Превью')),
                ('created_at', models.DateField(verbose_name='Дата создания')),
                ('is_published', models.BooleanField(verbose_name='Признак публикации')),
                ('views_number', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['head'],
            },
        ),
    ]
